model_name_or_path: KathirKs/gemma-2b-hindi

trainer:
  checkpointer:
    base_path: "gs://fineweb-edu-v4/sft/"

  tracker:
    type: wandb
    project: "indic-gemma"
    tags: ["fineweb", "gemma","alpaca", "sft"]

  mp: p=bfloat16,c=bfloat16
  train_batch_size: 256 # set for v4-128 TPU
  num_train_steps: 1000
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"

optimizer:
  learning_rate: 2e-5
  weight_decay: 0.0

supervised_data:
  hf_dataset_name: "iamshnoo/alpaca-cleaned-hindi"
  hf_dataset_split: "train"
  input_field: "instruction"
  output_field: "output"
  cache_dir: "gs://fineweb-edu-v4/alpaca-cleaned-hindi"

max_tune_length: 8192
trust_remote_code: false
model_cache_dir: null

hf_save_path: "sft_hf_ckpts"
hf_upload: KathirKs/gemma-2b-hindi-sft-alpaca
hf_save_steps: 500